"use client"
import React, { useContext, useState, useEffect, useCallback, useRef } from 'react';
import dynamic from 'next/dynamic';
import Lookup from '@/data/Lookup';
import { MessagesContext } from '@/context/MessagesContext';
import Prompt from '@/data/Prompt';
import { useConvex, useMutation } from 'convex/react';
import { useParams } from 'next/navigation';
import { api } from '@/convex/_generated/api';
import { Loader2Icon, Download, Sparkles, Code2, Eye } from 'lucide-react';
import JSZip from 'jszip';

const SandpackProvider = dynamic(() => import("@codesandbox/sandpack-react").then(mod => mod.SandpackProvider), { ssr: false });
const SandpackLayout = dynamic(() => import("@codesandbox/sandpack-react").then(mod => mod.SandpackLayout), { ssr: false });
const SandpackCodeEditor = dynamic(() => import("@codesandbox/sandpack-react").then(mod => mod.SandpackCodeEditor), { ssr: false });
const SandpackPreview = dynamic(() => import("@codesandbox/sandpack-react").then(mod => mod.SandpackPreview), { ssr: false });
const SandpackFileExplorer = dynamic(() => import("@codesandbox/sandpack-react").then(mod => mod.SandpackFileExplorer), { ssr: false });

function CodeView() {
    const { id } = useParams();
    const [activeTab, setActiveTab] = useState('code');
    const [files, setFiles] = useState(Lookup?.DEFAULT_FILE);
    const { messages } = useContext(MessagesContext);
    const UpdateFiles = useMutation(api.workspace.UpdateFiles);
    const convex = useConvex();
    const [loading, setLoading] = useState(false);
    const hasAutoGenerated = useRef(false);

    const preprocessFiles = useCallback((files) => {
        const processed = {};
        Object.entries(files).forEach(([path, content]) => {
            if (typeof content === 'string') {
                processed[path] = { code: content };
            } else if (content && typeof content === 'object') {
                if (!content.code && typeof content === 'object') {
                    processed[path] = { code: JSON.stringify(content, null, 2) };
                } else {
                    processed[path] = content;
                }
            }
        });
        return processed;
    }, []);

    const GetFiles = useCallback(async () => {
        const result = await convex.query(api.workspace.GetWorkspace, {
            workspaceId: id
        });
        const processedFiles = preprocessFiles(result?.fileData || {});
        const mergedFiles = { ...Lookup.DEFAULT_FILE, ...processedFiles };
        setFiles(mergedFiles);
    }, [id, convex, preprocessFiles]);

    useEffect(() => {
        id && GetFiles();
    }, [id, GetFiles]);

    const GenerateAiCode = useCallback(async () => {
        if (loading) return;
        setLoading(true);

        const PROMPT = JSON.stringify(messages) + " " + Prompt.CODE_GEN_PROMPT;

        try {
            const response = await fetch('/website-builder/api/gen-ai-code', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ prompt: PROMPT }),
            });

            const reader = response.body.getReader();
            const decoder = new TextDecoder();
            let finalData = null;

            while (true) {
                const { done, value } = await reader.read();
                if (done) break;

                const chunk = decoder.decode(value);
                const lines = chunk.split('\n');

                for (const line of lines) {
                    if (line.startsWith('data: ')) {
                        try {
                            const data = JSON.parse(line.slice(6));
                            if (data.done && data.final) {
                                finalData = data.final;
                            }
                        } catch (e) {
                            // Skip invalid JSON
                        }
                    }
                }
            }

            if (finalData && finalData.files) {
                const processedAiFiles = preprocessFiles(finalData.files || {});
                const mergedFiles = { ...Lookup.DEFAULT_FILE, ...processedAiFiles };
                setFiles(mergedFiles);

                await UpdateFiles({
                    workspaceId: id,
                    files: finalData.files
                });
            }
        } catch (error) {
            console.error('Error generating AI code:', error);
        } finally {
            setLoading(false);
        }
    }, [messages, id, UpdateFiles, preprocessFiles, loading]);

    // Auto-generate only once on first user message (initial project creation)
    useEffect(() => {
        if (messages?.length > 0 && !hasAutoGenerated.current) {
            const role = messages[messages?.length - 1].role;
            if (role === 'user') {
                hasAutoGenerated.current = true;
                GenerateAiCode();
            }
        }
    }, [messages, GenerateAiCode]);

    const downloadFiles = useCallback(async () => {
        try {
            const zip = new JSZip();

            Object.entries(files).forEach(([filename, content]) => {
                let fileContent;
                if (typeof content === 'string') {
                    fileContent = content;
                } else if (content && typeof content === 'object') {
                    if (content.code) {
                        fileContent = content.code;
                    } else {
                        fileContent = JSON.stringify(content, null, 2);
                    }
                }

                if (fileContent) {
                    const cleanFileName = filename.startsWith('/') ? filename.slice(1) : filename;
                    zip.file(cleanFileName, fileContent);
                }
            });

            const packageJson = {
                name: "generated-project",
                version: "1.0.0",
                private: true,
                dependencies: Lookup.DEPENDANCY,
                scripts: {
                    "dev": "vite",
                    "build": "vite build",
                    "preview": "vite preview"
                }
            };
            zip.file("package.json", JSON.stringify(packageJson, null, 2));

            const blob = await zip.generateAsync({ type: "blob" });

            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'project-files.zip';
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);
        } catch (error) {
            console.error('Error downloading files:', error);
        }
    }, [files]);

    return (
        <div className='relative bg-[#1a1a2e] rounded-xl border border-gray-800 overflow-hidden'>
            {/* Toolbar */}
            <div className='bg-[#181818] w-full p-2 border-b border-gray-800'>
                <div className='flex items-center justify-between flex-wrap gap-2'>
                    <div className='flex items-center gap-2'>
                        <button
                            onClick={() => setActiveTab('code')}
                            className={`flex items-center gap-1.5 text-sm cursor-pointer px-3 py-1.5 rounded-full transition-all ${
                                activeTab === 'code'
                                    ? 'text-blue-400 bg-blue-500/20'
                                    : 'text-gray-400 hover:text-gray-300'
                            }`}
                        >
                            <Code2 className="h-4 w-4" />
                            Code
                        </button>
                        <button
                            onClick={() => setActiveTab('preview')}
                            className={`flex items-center gap-1.5 text-sm cursor-pointer px-3 py-1.5 rounded-full transition-all ${
                                activeTab === 'preview'
                                    ? 'text-blue-400 bg-blue-500/20'
                                    : 'text-gray-400 hover:text-gray-300'
                            }`}
                        >
                            <Eye className="h-4 w-4" />
                            Preview
                        </button>
                    </div>

                    <div className='flex items-center gap-2'>
                        <button
                            onClick={GenerateAiCode}
                            disabled={loading}
                            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm transition-all ${
                                loading
                                    ? 'bg-gray-700 text-gray-400 cursor-not-allowed'
                                    : 'bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 text-white'
                            }`}
                        >
                            {loading ? (
                                <Loader2Icon className="animate-spin h-4 w-4" />
                            ) : (
                                <Sparkles className="h-4 w-4" />
                            )}
                            <span className="hidden sm:inline">{loading ? 'Generating...' : 'Generate'}</span>
                        </button>
                        <button
                            onClick={downloadFiles}
                            className="flex items-center gap-1.5 bg-blue-500 hover:bg-blue-600 text-white px-3 py-1.5 rounded-full text-sm transition-all"
                        >
                            <Download className="h-4 w-4" />
                            <span className="hidden sm:inline">Download</span>
                        </button>
                    </div>
                </div>
            </div>

            {/* Sandpack */}
            <SandpackProvider
                files={files}
                template="react"
                theme={'dark'}
                customSetup={{
                    dependencies: {
                        ...Lookup.DEPENDANCY
                    },
                    entry: '/index.js'
                }}
                options={{
                    externalResources: ['https://cdn.tailwindcss.com'],
                    bundlerTimeoutSecs: 120,
                    recompileMode: "immediate",
                    recompileDelay: 300
                }}
            >
                <div className="relative">
                    <SandpackLayout>
                        {activeTab === 'code' ? (
                            <>
                                <SandpackFileExplorer style={{ height: '75vh' }} />
                                <SandpackCodeEditor
                                    style={{ height: '75vh' }}
                                    showTabs
                                    showLineNumbers
                                    showInlineErrors
                                    wrapContent
                                />
                            </>
                        ) : (
                            <SandpackPreview
                                style={{ height: '75vh' }}
                                showNavigator={true}
                                showOpenInCodeSandbox={false}
                                showRefreshButton={true}
                            />
                        )}
                    </SandpackLayout>
                </div>
            </SandpackProvider>

            {/* Loading Overlay */}
            {loading && (
                <div className='p-10 bg-gray-900/80 backdrop-blur-sm absolute top-0 rounded-lg w-full h-full flex flex-col items-center justify-center gap-3'>
                    <Loader2Icon className='animate-spin h-10 w-10 text-emerald-400' />
                    <h2 className='text-white text-lg font-medium'>Generating your project...</h2>
                    <p className='text-gray-400 text-sm'>Creating components with AI</p>
                </div>
            )}
        </div>
    );
}

export default CodeView;
